project:
  type: book
  output-dir: docs

book:
  title: "Arbor: The Complete R Tutorial Book"
  subtitle: "From Semantic Segmentation to Quantitative Structure Modelling"
  author:
    - name: "Jean-Romain Roussel"
      affiliation: "r-lidar"
  date: today
  description: "A comprehensive guide to LiDAR data processing, tree segmentation, and structural analysis in R."
  chapters:
    - index.qmd
    - arbor.qmd
    - preparation.qmd
    - decimation.qmd
    - ground.qmd
    - semantic.qmd
    - instance.qmd
    - qsm.qmd
    - qsf.qmd
    - forestry.qmd
    - results.qmd
    - faq.qmd
    - mre.qmd
    - spec.qmd
    - cmd.qmd

format:
  html:
    theme: cosmo
    css: style.css
    self-contained: false
    include-in-header:
      text: |
        <a title="Google Analytics Alternative" href="https://clicky.com/101510612"><img alt="Clicky" src="//static.getclicky.com/media/links/badge.gif" border="0" /></a>
        <script async data-id="101510612" src="//static.getclicky.com/js"></script>


lightbox: true


